# DSCI 619 Deep Learning Project 1
## Ben Miller

In [6]:
import pandas as pd
import os
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, root_mean_squared_error, mean_absolute_error
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

## Load the dataset into memory

In [7]:
df = pd.read_csv("airfoil_self_noise.dat", sep="\t")
# name the columns
df.columns = ["Frequency", "Angle of Attack", "Chord Length", "Free Stream Velocity", "Suction Side Displacement Thickness", "Scaled Sound Pressure Level"]
df.head()

,Frequency,Angle of Attack,Chord Length,Free Stream Velocity,Suction Side Displacement Thickness,Scaled Sound Pressure Level
0,1000,0.0,0.3048,71.3,0.002663,125.201
1,1250,0.0,0.3048,71.3,0.002663,125.951
2,1600,0.0,0.3048,71.3,0.002663,127.591
3,2000,0.0,0.3048,71.3,0.002663,127.461
4,2500,0.0,0.3048,71.3,0.002663,125.571

## Check for missing values

In [8]:
df.isnull().sum(axis=0)

Frequency                              0
Angle of Attack                        0
Chord Length                           0
Free Stream Velocity                   0
Suction Side Displacement Thickness    0
Scaled Sound Pressure Level            0
dtype: int64

## Split the training data

In [9]:
X = df.drop("Scaled Sound Pressure Level", axis=1)
y = df["Scaled Sound Pressure Level"]

# 80% training and 20% testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 42)

## Build a simple linear regression to forecast "Scaled sound pressure level" using scikit-learn package

In [10]:
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
test_error = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error of Linear Regression: {test_error:.4f}")

Mean Squared Error of Linear Regression: 21.2594

## Preprocess the data using the normalization method

In [11]:
## MinMaxScaler scales the features to a range of [0, 1]
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## Create a deep learning regression model with TensorFlow

In [12]:
# Helper function to build a TensorFlow model
def build_TensorFlow_model(num_neurons, optimization_algorithm):
    model = keras.Sequential()
    model.add(layers.Dense(num_neurons, activation='relu'))
    model.add(layers.Dense(1))
    
    model.compile(optimizer=optimization_algorithm,loss='mse')
    
    return model

In [13]:
# Helper function to print Error metrics
def print_evaluation_metrics(y_true, y_pred):
    mse = mean_squared_error(y_true, y_pred)
    rmse = root_mean_squared_error(y_true, y_pred)
    mae = mean_absolute_error(y_true, y_pred)
    
    print(f"Mean Squared Error: {mse:.4f}")
    print(f"Root Mean Squared Error: {rmse:.4f}")
    print(f"Mean Absolute Error: {mae:.4f}")

In [14]:
tf.random.set_seed(1)
# start with 20 neurons in the hidden layer and adam optimization algorithm
model = build_TensorFlow_model(num_neurons=20, optimization_algorithm='adam')

model.fit(x=X_train,y=y_train,batch_size=64,epochs=500,
          validation_data=(X_test,y_test)
          )

Epoch 1/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 15625.4707 - val_loss: 15558.7197
Epoch 2/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 15574.9795 - val_loss: 15509.1328
Epoch 3/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 15521.6289 - val_loss: 15455.5947
Epoch 4/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 15462.9561 - val_loss: 15395.0361
Epoch 5/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 15395.7637 - val_loss: 15324.7061
Epoch 6/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 15317.5371 - val_loss: 15241.9834
Epoch 7/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 15225.7969 - val_loss: 15144.4033
Epoch 8/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 15117.5938 - val_loss: 15029.4434
Epoch 9/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 14990.7012 - val_loss: 14896.7012
Epoch 10/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 14847.2939 - val_loss: 14750.5479
Epoch 11/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 14691.7520 - val_loss: 14594.1016
Epoch 12/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 14526.1680 - val_loss: 14428.3867
Epoch 13/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 14351.1553 - val_loss: 14253.6299
Epoch 14/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 14166.9307 - val_loss: 14070.0420
Epoch 15/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 13973.7432 - val_loss: 13877.9170
Epoch 16/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 13771.8984 - val_loss: 13677.4961
Epoch 17/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 13561.6650 - val_loss: 13469.0674
Epoch 18/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 13343.3535 - val_loss: 13252.9141
Epoch 19/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 13117.2021 - val_loss: 13029.1201
Epoch 20/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 12883.1387 - val_loss: 12797.4912
Epoch 21/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12640.9092 - val_loss: 12557.6738
Epoch 22/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12390.1191 - val_loss: 12309.3389
Epoch 23/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12130.6562 - val_loss: 12052.6592
Epoch 24/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 11862.9795 - val_loss: 11788.3535
Epoch 25/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 11587.9971 - val_loss: 11517.4111
Epoch 26/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 11306.7607 - val_loss: 11240.8398
Epoch 27/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 11020.2910 - val_loss: 10959.5752
Epoch 28/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10729.5098 - val_loss: 10674.4180
Epoch 29/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10435.2119 - val_loss: 10386.0557
Epoch 30/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10137.9834 - val_loss: 10094.8467
Epoch 31/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9837.8193 - val_loss: 9800.0576
Epoch 32/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9533.3428 - val_loss: 9499.5713
Epoch 33/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9222.6211 - val_loss: 9192.5439
Epoch 34/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8906.1104 - val_loss: 8881.8643
Epoch 35/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8587.8525 - val_loss: 8570.7646
Epoch 36/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8270.1191 - val_loss: 8260.7656
Epoch 37/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7954.2583 - val_loss: 7952.9868
Epoch 38/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7641.3120 - val_loss: 7648.3315
Epoch 39/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7332.1523 - val_loss: 7347.5771
Epoch 40/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7027.5312 - val_loss: 7051.4004
Epoch 41/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6728.1089 - val_loss: 6760.4014
Epoch 42/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6434.4790 - val_loss: 6475.1245
Epoch 43/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6147.1738 - val_loss: 6196.0591
Epoch 44/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5866.6729 - val_loss: 5923.6445
Epoch 45/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5593.4053 - val_loss: 5658.2769
Epoch 46/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5327.7559 - val_loss: 5400.3086
Epoch 47/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5070.0625 - val_loss: 5150.0513
Epoch 48/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4820.6226 - val_loss: 4907.7759
Epoch 49/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4579.6890 - val_loss: 4673.7134
Epoch 50/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4347.4756 - val_loss: 4448.0542
Epoch 51/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4124.1509 - val_loss: 4230.9521
Epoch 52/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3909.8467 - val_loss: 4022.5242
Epoch 53/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3704.6545 - val_loss: 3822.8467
Epoch 54/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3508.6279 - val_loss: 3631.9626
Epoch 55/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3321.7805 - val_loss: 3449.8774
Epoch 56/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3144.0918 - val_loss: 3276.5652
Epoch 57/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2975.5042 - val_loss: 3111.9644
Epoch 58/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2815.9285 - val_loss: 2955.9827
Epoch 59/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2665.2400 - val_loss: 2808.4983
Epoch 60/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2523.2871 - val_loss: 2669.3618
Epoch 61/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2389.8875 - val_loss: 2538.3940
Epoch 62/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2264.8318 - val_loss: 2415.3955
Epoch 63/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2147.8884 - val_loss: 2300.1431
Epoch 64/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 2038.8031 - val_loss: 2192.3909
Epoch 65/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1937.3016 - val_loss: 2091.8804
Epoch 66/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1843.0939 - val_loss: 1998.3345
Epoch 67/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1755.8749 - val_loss: 1911.4629
Epoch 68/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1675.3281 - val_loss: 1830.9678
Epoch 69/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1601.1285 - val_loss: 1756.5399
Epoch 70/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1532.9443 - val_loss: 1687.8677
Epoch 71/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1470.4398 - val_loss: 1624.6351
Epoch 72/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1413.2784 - val_loss: 1566.5254
Epoch 73/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1361.1248 - val_loss: 1513.2233
Epoch 74/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1313.6466 - val_loss: 1464.4183
Epoch 75/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1270.5176 - val_loss: 1419.8032
Epoch 76/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1231.4183 - val_loss: 1379.0800
Epoch 77/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1196.0389 - val_loss: 1341.9579
Epoch 78/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1164.0800 - val_loss: 1308.1573
Epoch 79/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1135.2543 - val_loss: 1277.4098
Epoch 80/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1109.2878 - val_loss: 1249.4590
Epoch 81/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1085.9204 - val_loss: 1224.0607
Epoch 82/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1064.9058 - val_loss: 1200.9849
Epoch 83/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1046.0138 - val_loss: 1180.0159
Epoch 84/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1029.0291 - val_loss: 1160.9514
Epoch 85/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1013.7506 - val_loss: 1143.6030
Epoch 86/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 999.9938 - val_loss: 1127.7960
Epoch 87/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 987.5881 - val_loss: 1113.3700
Epoch 88/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 976.3779 - val_loss: 1100.1772
Epoch 89/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 966.2208 - val_loss: 1088.0831
Epoch 90/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 956.9886 - val_loss: 1076.9642
Epoch 91/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 948.5645 - val_loss: 1066.7091
Epoch 92/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 940.8443 - val_loss: 1057.2172
Epoch 93/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 933.7347 - val_loss: 1048.3977
Epoch 94/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 927.1523 - val_loss: 1040.1694
Epoch 95/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 921.0235 - val_loss: 1032.4600
Epoch 96/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 915.2835 - val_loss: 1025.2040
Epoch 97/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 909.8749 - val_loss: 1018.3444
Epoch 98/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 904.7473 - val_loss: 1011.8300
Epoch 99/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 899.8572 - val_loss: 1005.6160
Epoch 100/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 895.1669 - val_loss: 999.6629
Epoch 101/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 890.6433 - val_loss: 993.9351
Epoch 102/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 886.2583 - val_loss: 988.4030
Epoch 103/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 881.9876 - val_loss: 983.0391
Epoch 104/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 877.8102 - val_loss: 977.8201
Epoch 105/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 873.7087 - val_loss: 972.7252
Epoch 106/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 869.6678 - val_loss: 967.7373
Epoch 107/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 865.6746 - val_loss: 962.8405
Epoch 108/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 861.7191 - val_loss: 958.0211
Epoch 109/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 857.7915 - val_loss: 953.2675
Epoch 110/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 853.8848 - val_loss: 948.5695
Epoch 111/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 849.9926 - val_loss: 943.9181
Epoch 112/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 846.1097 - val_loss: 939.3060
Epoch 113/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 842.2318 - val_loss: 934.7259
Epoch 114/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 838.3554 - val_loss: 930.1729
Epoch 115/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 834.4775 - val_loss: 925.6404
Epoch 116/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 830.5959 - val_loss: 921.1255
Epoch 117/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 826.7087 - val_loss: 916.6235
Epoch 118/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 822.8144 - val_loss: 912.1314
Epoch 119/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 818.9116 - val_loss: 907.6466
Epoch 120/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 814.9993 - val_loss: 903.1660
Epoch 121/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 811.0771 - val_loss: 898.6879
Epoch 122/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 807.1442 - val_loss: 894.2099
Epoch 123/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 803.2002 - val_loss: 889.7311
Epoch 124/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 799.2449 - val_loss: 885.2494
Epoch 125/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 795.2779 - val_loss: 880.7640
Epoch 126/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 791.2992 - val_loss: 876.2738
Epoch 127/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 787.3086 - val_loss: 871.7772
Epoch 128/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 783.3061 - val_loss: 867.2744
Epoch 129/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 779.2920 - val_loss: 862.7637
Epoch 130/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 775.2659 - val_loss: 858.2457
Epoch 131/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 771.2283 - val_loss: 853.7193
Epoch 132/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 767.1789 - val_loss: 849.1841
Epoch 133/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 763.1181 - val_loss: 844.6396
Epoch 134/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 759.0460 - val_loss: 840.0861
Epoch 135/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 754.9625 - val_loss: 835.5226
Epoch 136/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 750.8680 - val_loss: 830.9495
Epoch 137/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 746.7626 - val_loss: 826.3664
Epoch 138/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 742.6464 - val_loss: 821.7736
Epoch 139/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 738.5196 - val_loss: 817.1706
Epoch 140/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 734.3823 - val_loss: 812.5574
Epoch 141/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 730.2347 - val_loss: 807.9348
Epoch 142/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 726.0770 - val_loss: 803.3017
Epoch 143/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 721.9094 - val_loss: 798.6588
Epoch 144/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 717.7321 - val_loss: 794.0061
Epoch 145/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 713.5453 - val_loss: 789.3436
Epoch 146/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 709.3489 - val_loss: 784.6714
Epoch 147/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 705.1434 - val_loss: 779.9894
Epoch 148/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 700.9289 - val_loss: 775.2985
Epoch 149/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 696.7056 - val_loss: 770.5982
Epoch 150/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 692.4734 - val_loss: 765.8889
Epoch 151/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 688.2330 - val_loss: 761.1707
Epoch 152/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 683.9843 - val_loss: 756.4436
Epoch 153/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 679.7274 - val_loss: 751.7078
Epoch 154/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 675.4626 - val_loss: 746.9637
Epoch 155/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 671.1903 - val_loss: 742.2119
Epoch 156/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 666.9102 - val_loss: 737.4518
Epoch 157/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 662.6229 - val_loss: 732.6837
Epoch 158/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 658.3286 - val_loss: 727.9082
Epoch 159/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 654.0273 - val_loss: 723.1257
Epoch 160/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 649.7195 - val_loss: 718.3356
Epoch 161/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 645.4050 - val_loss: 713.5390
Epoch 162/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 641.0843 - val_loss: 708.7355
Epoch 163/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 636.7576 - val_loss: 703.9260
Epoch 164/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 632.4250 - val_loss: 699.1097
Epoch 165/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 628.0867 - val_loss: 694.2878
Epoch 166/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 623.7430 - val_loss: 689.4600
Epoch 167/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 619.3940 - val_loss: 684.6268
Epoch 168/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 615.0402 - val_loss: 679.7887
Epoch 169/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 610.6815 - val_loss: 674.9451
Epoch 170/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 606.3183 - val_loss: 670.0970
Epoch 171/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 601.9509 - val_loss: 665.2444
Epoch 172/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 597.5793 - val_loss: 660.3879
Epoch 173/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 593.2039 - val_loss: 655.5274
Epoch 174/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 588.8250 - val_loss: 650.6630
Epoch 175/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 584.4426 - val_loss: 645.7953
Epoch 176/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 580.0571 - val_loss: 640.9247
Epoch 177/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 575.6689 - val_loss: 636.0510
Epoch 178/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 571.2781 - val_loss: 631.1746
Epoch 179/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 566.8847 - val_loss: 626.2961
Epoch 180/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 562.4893 - val_loss: 621.4159
Epoch 181/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 558.0920 - val_loss: 616.5337
Epoch 182/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 553.6933 - val_loss: 611.6502
Epoch 183/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 549.2931 - val_loss: 606.7658
Epoch 184/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 544.8922 - val_loss: 601.8804
Epoch 185/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 540.4902 - val_loss: 596.9944
Epoch 186/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 536.0878 - val_loss: 592.1086
Epoch 187/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 531.6852 - val_loss: 587.2225
Epoch 188/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 527.2828 - val_loss: 582.3373
Epoch 189/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 522.8808 - val_loss: 577.4528
Epoch 190/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 518.4794 - val_loss: 572.5692
Epoch 191/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 514.0789 - val_loss: 567.6872
Epoch 192/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 509.6797 - val_loss: 562.8068
Epoch 193/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 505.2820 - val_loss: 557.9286
Epoch 194/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 500.8863 - val_loss: 553.0527
Epoch 195/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 496.4928 - val_loss: 548.1798
Epoch 196/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 492.1017 - val_loss: 543.3101
Epoch 197/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 487.7135 - val_loss: 538.4437
Epoch 198/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 483.3285 - val_loss: 533.5814
Epoch 199/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 478.9470 - val_loss: 528.7229
Epoch 200/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 474.5692 - val_loss: 523.8695
Epoch 201/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 470.1956 - val_loss: 519.0206
Epoch 202/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 465.8265 - val_loss: 514.1774
Epoch 203/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 461.4624 - val_loss: 509.3395
Epoch 204/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 457.1033 - val_loss: 504.5081
Epoch 205/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 452.7499 - val_loss: 499.6831
Epoch 206/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 448.4023 - val_loss: 494.8650
Epoch 207/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 444.0609 - val_loss: 490.0540
Epoch 208/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 439.7261 - val_loss: 485.2505
Epoch 209/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 435.3984 - val_loss: 480.4554
Epoch 210/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 431.0780 - val_loss: 475.6685
Epoch 211/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 426.7653 - val_loss: 470.8908
Epoch 212/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 422.4608 - val_loss: 466.1219
Epoch 213/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 418.1646 - val_loss: 461.3630
Epoch 214/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 413.8774 - val_loss: 456.6143
Epoch 215/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 409.5995 - val_loss: 451.8760
Epoch 216/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 405.3311 - val_loss: 447.1487
Epoch 217/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 401.0728 - val_loss: 442.4327
Epoch 218/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 396.8250 - val_loss: 437.7287
Epoch 219/500

In [15]:
y_pred = model.predict(X_test)
print_evaluation_metrics(y_test, y_pred)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
Mean Squared Error: 21.5678
Root Mean Squared Error: 4.6441
Mean Absolute Error: 3.5558

## Attempt to improve the performance by adjusting the number of neurons and optimization algorithm

In [16]:
# increase the number of neurons to 50 and change the optimization algorithm to stochastic gradient descent (sgd)
improved_model = build_TensorFlow_model(num_neurons=50, optimization_algorithm='sgd')

improved_model.fit(x=X_train,y=y_train,batch_size=64,epochs=500,
          validation_data=(X_test,y_test)
          )

Epoch 1/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 10885.2705 - val_loss: 9853.6846
Epoch 2/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7288.8242 - val_loss: 5079.7915
Epoch 3/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3662.7988 - val_loss: 2379.3455
Epoch 4/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1726.0380 - val_loss: 1127.4414
Epoch 5/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 826.9630 - val_loss: 547.3548
Epoch 6/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 409.5402 - val_loss: 278.7581
Epoch 7/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 215.6995 - val_loss: 154.5230
Epoch 8/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 125.6577 - val_loss: 97.1510
Epoch 9/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 83.8140 - val_loss: 70.7187
Epoch 10/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 64.3560 - val_loss: 58.5831
Epoch 11/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 55.2993 - val_loss: 53.0406
Epoch 12/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 51.0781 - val_loss: 50.5293
Epoch 13/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 49.1067 - val_loss: 49.4054
Epoch 14/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 48.1834 - val_loss: 48.9120
Epoch 15/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.7492 - val_loss: 48.7023
Epoch 16/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.5438 - val_loss: 48.6181
Epoch 17/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.4458 - val_loss: 48.5880
Epoch 18/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3985 - val_loss: 48.5801
Epoch 19/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3753 - val_loss: 48.5805
Epoch 20/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.3637 - val_loss: 48.5836
Epoch 21/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3577 - val_loss: 48.5869
Epoch 22/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3545 - val_loss: 48.5898
Epoch 23/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3528 - val_loss: 48.5920
Epoch 24/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3518 - val_loss: 48.5936
Epoch 25/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3512 - val_loss: 48.5948
Epoch 26/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3509 - val_loss: 48.5956
Epoch 27/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3507 - val_loss: 48.5962
Epoch 28/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.3505 - val_loss: 48.5966
Epoch 29/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.3504 - val_loss: 48.5969
Epoch 30/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3504 - val_loss: 48.5971
Epoch 31/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.3503 - val_loss: 48.5972
Epoch 32/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5973
Epoch 33/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5974
Epoch 34/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5974
Epoch 35/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5974
Epoch 36/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.3503 - val_loss: 48.5974
Epoch 37/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 38/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 39/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 40/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 41/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 42/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 43/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 44/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 45/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 46/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 47/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 48/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 49/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 50/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 51/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 52/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 53/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 54/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 55/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 56/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 57/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 58/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 59/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 60/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 61/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 62/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 63/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 64/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 65/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 66/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 67/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 68/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 69/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 70/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 71/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 72/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 73/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 74/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 75/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 76/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 77/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 78/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 79/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 80/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 81/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 82/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 83/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 84/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 85/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 86/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 87/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 88/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 89/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 90/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 91/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 92/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 93/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 94/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 95/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 96/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 97/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 98/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 99/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 100/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 101/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 102/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 103/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 104/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 105/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 106/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 107/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 108/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 109/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 110/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 111/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 112/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 113/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 114/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 115/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 116/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 117/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 118/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 119/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 120/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 121/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 122/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 123/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 124/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 125/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 126/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 127/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 128/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 129/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 130/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 131/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 132/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 133/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 134/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 135/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 136/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 137/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 138/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 139/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 140/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 141/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 142/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 143/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 144/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 145/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 146/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 147/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 148/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 149/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 150/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 151/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 152/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 153/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 154/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 155/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 156/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 157/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 158/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 159/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 160/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 161/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 162/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 163/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 164/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 165/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 166/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 167/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 168/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 169/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 170/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 171/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 172/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 173/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 174/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 175/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 176/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 177/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 178/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 179/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 180/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 181/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 182/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 183/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 184/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 185/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 186/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 187/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 188/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 189/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 190/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 191/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 192/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 193/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 194/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 195/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 196/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 197/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 198/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 199/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 200/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 201/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 202/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 203/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 204/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 205/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 206/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 207/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 208/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 209/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 210/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 211/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 212/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 213/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 214/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 215/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 216/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 217/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 218/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 219/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 220/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 221/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 222/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 223/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 224/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 225/500
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.3503 - val_loss: 48.5975
Epoch 226/500

In [17]:
y_pred = improved_model.predict(X_test)
print_evaluation_metrics(y_test, y_pred)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
Mean Squared Error: 48.5975
Root Mean Squared Error: 6.9712
Mean Absolute Error: 5.7169

## Create a deep learning regression model with PyTorch

In [18]:
X_train = torch.tensor(X_train.astype(np.float32))
y_train = torch.tensor(y_train.values.astype(np.float32).reshape(-1,1))

In [19]:
# define the child module class derivated from parent class of torch.nn.Module)
class LinearRegressionModel(torch.nn.Module):
    #define the constructor
    def __init__(self, input_size, hidden_size, output_size):
        super(LinearRegressionModel, self).__init__()
        # first layer: input -> hidden
        self.hidden = torch.nn.Linear(input_size, hidden_size) 
        # second layer: hidden -> output
        self.predict = torch.nn.Linear(hidden_size, output_size) 
    #override the forward function in this child class
    def forward(self, x):
        x = F.relu(self.hidden(x))     
        y_pred = self.predict(x)            
        return y_pred

In [20]:
def train_PyTorch_model(model, l, optimizer, X_train, y_train):
  #fix the random seeds for torch and np
  torch.manual_seed(1)
  np.random.seed(0)

  #set the number of epochs
  num_epochs = 500
  for epoch in range(num_epochs):
      #forward pass
      y_pred = model(X_train.requires_grad_())

      #calculate the loss
      loss= l(y_pred, y_train)
      #Set the gradients to be zero
      optimizer.zero_grad()
    
      #backward pass: calculate gradients
      loss.backward()

      #update the weights
      optimizer.step()
  
      print('epoch {0}, loss:{1:.4f}'.format(epoch, loss.item()))

In [21]:
# start with 20 neurons in the hidden layer and adam optimization algorithm
model = LinearRegressionModel(input_size = X_train.shape[1], hidden_size = 20, output_size = 1)
loss = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.05)
train_PyTorch_model(model, loss, optimizer, X_train, y_train)

epoch 0, loss:15679.5957
epoch 1, loss:15601.0986
epoch 2, loss:15513.7920
epoch 3, loss:15408.8145
epoch 4, loss:15281.1445
epoch 5, loss:15127.9814
epoch 6, loss:14947.5635
epoch 7, loss:14738.5166
epoch 8, loss:14499.6768
epoch 9, loss:14230.3281
epoch 10, loss:13929.9004
epoch 11, loss:13597.8115
epoch 12, loss:13233.3555
epoch 13, loss:12835.9365
epoch 14, loss:12404.9775
epoch 15, loss:11942.4785
epoch 16, loss:11449.5703
epoch 17, loss:10927.8301
epoch 18, loss:10378.7969
epoch 19, loss:9804.3965
epoch 20, loss:9207.1123
epoch 21, loss:8589.9521
epoch 22, loss:7956.6128
epoch 23, loss:7312.7021
epoch 24, loss:6664.5430
epoch 25, loss:6018.3530
epoch 26, loss:5380.7710
epoch 27, loss:4758.9409
epoch 28, loss:4160.4072
epoch 29, loss:3592.9763
epoch 30, loss:3064.5291
epoch 31, loss:2582.7698
epoch 32, loss:2154.9045
epoch 33, loss:1787.2452
epoch 34, loss:1484.7321
epoch 35, loss:1250.4006
epoch 36, loss:1084.8174
epoch 37, loss:985.5709
epoch 38, loss:946.9129
epoch 39, loss:959.7029
epoch 40, loss:1011.7922
epoch 41, loss:1088.9357
epoch 42, loss:1176.1871
epoch 43, loss:1259.5460
epoch 44, loss:1327.5074
epoch 45, loss:1372.1511
epoch 46, loss:1389.5795
epoch 47, loss:1379.6931
epoch 48, loss:1345.4827
epoch 49, loss:1292.0623
epoch 50, loss:1225.6515
epoch 51, loss:1152.6669
epoch 52, loss:1079.0043
epoch 53, loss:1009.5499
epoch 54, loss:947.9083
epoch 55, loss:896.3303
epoch 56, loss:855.7880
epoch 57, loss:826.1533
epoch 58, loss:806.4429
epoch 59, loss:795.0840
epoch 60, loss:790.1707
epoch 61, loss:789.6933
epoch 62, loss:791.7234
epoch 63, loss:794.5507
epoch 64, loss:796.7720
epoch 65, loss:797.3383
epoch 66, loss:795.5649
epoch 67, loss:791.1124
epoch 68, loss:783.9464
epoch 69, loss:774.2844
epoch 70, loss:762.5342
epoch 71, loss:749.2289
epoch 72, loss:734.9632
epoch 73, loss:720.3364
epoch 74, loss:705.9020
epoch 75, loss:692.1266
epoch 76, loss:679.3633
epoch 77, loss:667.8359
epoch 78, loss:657.6362
epoch 79, loss:648.7323
epoch 80, loss:640.9882
epoch 81, loss:634.1912
epoch 82, loss:628.0795
epoch 83, loss:622.3775
epoch 84, loss:616.8211
epoch 85, loss:611.1854
epoch 86, loss:605.2985
epoch 87, loss:599.0522
epoch 88, loss:592.4023
epoch 89, loss:585.3625
epoch 90, loss:577.9930
epoch 91, loss:570.3859
epoch 92, loss:562.6505
epoch 93, loss:554.8957
epoch 94, loss:547.2209
epoch 95, loss:539.7041
epoch 96, loss:532.3986
epoch 97, loss:525.3307
epoch 98, loss:518.5012
epoch 99, loss:511.8896
epoch 100, loss:505.4611
epoch 101, loss:499.1710
epoch 102, loss:492.9728
epoch 103, loss:486.8227
epoch 104, loss:480.6843
epoch 105, loss:474.5309
epoch 106, loss:468.3471
epoch 107, loss:462.1285
epoch 108, loss:455.8797
epoch 109, loss:449.6128
epoch 110, loss:443.3450
epoch 111, loss:437.0945
epoch 112, loss:430.8801
epoch 113, loss:424.7168
epoch 114, loss:418.6165
epoch 115, loss:412.5863
epoch 116, loss:406.6283
epoch 117, loss:400.7404
epoch 118, loss:394.9174
epoch 119, loss:389.1524
epoch 120, loss:383.4374
epoch 121, loss:377.7647
epoch 122, loss:372.1286
epoch 123, loss:366.5241
epoch 124, loss:360.9500
epoch 125, loss:355.4057
epoch 126, loss:349.8937
epoch 127, loss:344.4168
epoch 128, loss:338.9792
epoch 129, loss:333.5850
epoch 130, loss:328.2381
epoch 131, loss:322.9416
epoch 132, loss:317.6972
epoch 133, loss:312.5063
epoch 134, loss:307.3689
epoch 135, loss:302.2844
epoch 136, loss:297.2516
epoch 137, loss:292.2693
epoch 138, loss:287.3366
epoch 139, loss:282.4521
epoch 140, loss:277.6155
epoch 141, loss:272.8266
epoch 142, loss:268.0862
epoch 143, loss:263.3948
epoch 144, loss:258.7536
epoch 145, loss:254.1886
epoch 146, loss:249.6817
epoch 147, loss:245.2293
epoch 148, loss:240.8325
epoch 149, loss:236.4917
epoch 150, loss:232.2099
epoch 151, loss:227.9951
epoch 152, loss:223.8394
epoch 153, loss:219.7399
epoch 154, loss:215.6965
epoch 155, loss:211.7087
epoch 156, loss:207.7761
epoch 157, loss:203.8985
epoch 158, loss:200.0757
epoch 159, loss:196.3078
epoch 160, loss:192.5949
epoch 161, loss:188.9372
epoch 162, loss:185.3348
epoch 163, loss:181.7879
epoch 164, loss:178.2967
epoch 165, loss:174.8613
epoch 166, loss:171.4832
epoch 167, loss:168.1616
epoch 168, loss:164.8969
epoch 169, loss:161.6893
epoch 170, loss:158.5385
epoch 171, loss:155.4440
epoch 172, loss:152.4047
epoch 173, loss:149.4211
epoch 174, loss:146.4922
epoch 175, loss:143.6179
epoch 176, loss:140.7975
epoch 177, loss:138.0329
epoch 178, loss:135.3218
epoch 179, loss:132.6641
epoch 180, loss:130.0605
epoch 181, loss:127.5090
epoch 182, loss:125.0095
epoch 183, loss:122.5645
epoch 184, loss:120.1737
epoch 185, loss:117.8356
epoch 186, loss:115.5572
epoch 187, loss:113.3296
epoch 188, loss:111.1532
epoch 189, loss:109.0275
epoch 190, loss:106.9509
epoch 191, loss:104.9261
epoch 192, loss:102.9542
epoch 193, loss:101.0283
epoch 194, loss:99.1491
epoch 195, loss:97.3177
epoch 196, loss:95.5303
epoch 197, loss:93.7858
epoch 198, loss:92.0836
epoch 199, loss:90.4228
epoch 200, loss:88.8028
epoch 201, loss:87.2241
epoch 202, loss:85.6855
epoch 203, loss:84.1854
epoch 204, loss:82.7230
epoch 205, loss:81.2976
epoch 206, loss:79.9086
epoch 207, loss:78.5552
epoch 208, loss:77.2374
epoch 209, loss:75.9541
epoch 210, loss:74.7046
epoch 211, loss:73.4881
epoch 212, loss:72.3043
epoch 213, loss:71.1522
epoch 214, loss:70.0312
epoch 215, loss:68.9406
epoch 216, loss:67.8792
epoch 217, loss:66.8466
epoch 218, loss:65.8418
epoch 219, loss:64.8643
epoch 220, loss:63.9133
epoch 221, loss:62.9883
epoch 222, loss:62.0889
epoch 223, loss:61.2140
epoch 224, loss:60.3631
epoch 225, loss:59.5355
epoch 226, loss:58.7307
epoch 227, loss:57.9482
epoch 228, loss:57.1873
epoch 229, loss:56.4471
epoch 230, loss:55.7272
epoch 231, loss:55.0270
epoch 232, loss:54.3460
epoch 233, loss:53.6836
epoch 234, loss:53.0391
epoch 235, loss:52.4121
epoch 236, loss:51.8021
epoch 237, loss:51.2085
epoch 238, loss:50.6308
epoch 239, loss:50.0685
epoch 240, loss:49.5213
epoch 241, loss:48.9886
epoch 242, loss:48.4702
epoch 243, loss:47.9656
epoch 244, loss:47.4742
epoch 245, loss:46.9956
epoch 246, loss:46.5294
epoch 247, loss:46.0753
epoch 248, loss:45.6330
epoch 249, loss:45.2021
epoch 250, loss:44.7820
epoch 251, loss:44.3725
epoch 252, loss:43.9732
epoch 253, loss:43.5839
epoch 254, loss:43.2043
epoch 255, loss:42.8336
epoch 256, loss:42.4720
epoch 257, loss:42.1190
epoch 258, loss:41.7744
epoch 259, loss:41.4381
epoch 260, loss:41.1096
epoch 261, loss:40.7886
epoch 262, loss:40.4749
epoch 263, loss:40.1684
epoch 264, loss:39.8689
epoch 265, loss:39.5761
epoch 266, loss:39.2898
epoch 267, loss:39.0099
epoch 268, loss:38.7359
epoch 269, loss:38.4679
epoch 270, loss:38.2057
epoch 271, loss:37.9490
epoch 272, loss:37.6978
epoch 273, loss:37.4518
epoch 274, loss:37.2109
epoch 275, loss:36.9749
epoch 276, loss:36.7437
epoch 277, loss:36.5171
epoch 278, loss:36.2951
epoch 279, loss:36.0775
epoch 280, loss:35.8641
epoch 281, loss:35.6549
epoch 282, loss:35.4497
epoch 283, loss:35.2484
epoch 284, loss:35.0509
epoch 285, loss:34.8570
epoch 286, loss:34.6668
epoch 287, loss:34.4800
epoch 288, loss:34.2967
epoch 289, loss:34.1166
epoch 290, loss:33.9399
epoch 291, loss:33.7663
epoch 292, loss:33.5959
epoch 293, loss:33.4285
epoch 294, loss:33.2641
epoch 295, loss:33.1025
epoch 296, loss:32.9437
epoch 297, loss:32.7875
epoch 298, loss:32.6340
epoch 299, loss:32.4830
epoch 300, loss:32.3346
epoch 301, loss:32.1887
epoch 302, loss:32.0452
epoch 303, loss:31.9040
epoch 304, loss:31.7651
epoch 305, loss:31.6286
epoch 306, loss:31.4942
epoch 307, loss:31.3620
epoch 308, loss:31.2320
epoch 309, loss:31.1041
epoch 310, loss:30.9782
epoch 311, loss:30.8544
epoch 312, loss:30.7325
epoch 313, loss:30.6125
epoch 314, loss:30.4944
epoch 315, loss:30.3781
epoch 316, loss:30.2637
epoch 317, loss:30.1510
epoch 318, loss:30.0401
epoch 319, loss:29.9310
epoch 320, loss:29.8235
epoch 321, loss:29.7177
epoch 322, loss:29.6135
epoch 323, loss:29.5109
epoch 324, loss:29.4100
epoch 325, loss:29.3107
epoch 326, loss:29.2129
epoch 327, loss:29.1166
epoch 328, loss:29.0218
epoch 329, loss:28.9285
epoch 330, loss:28.8366
epoch 331, loss:28.7461
epoch 332, loss:28.6571
epoch 333, loss:28.5694
epoch 334, loss:28.4831
epoch 335, loss:28.3981
epoch 336, loss:28.3145
epoch 337, loss:28.2321
epoch 338, loss:28.1511
epoch 339, loss:28.0714
epoch 340, loss:27.9930
epoch 341, loss:27.9158
epoch 342, loss:27.8398
epoch 343, loss:27.7649
epoch 344, loss:27.6913
epoch 345, loss:27.6188
epoch 346, loss:27.5474
epoch 347, loss:27.4772
epoch 348, loss:27.4080
epoch 349, loss:27.3397
epoch 350, loss:27.2724
epoch 351, loss:27.2061
epoch 352, loss:27.1408
epoch 353, loss:27.0764
epoch 354, loss:27.0129
epoch 355, loss:26.9503
epoch 356, loss:26.8884
epoch 357, loss:26.8275
epoch 358, loss:26.7675
epoch 359, loss:26.7081
epoch 360, loss:26.6496
epoch 361, loss:26.5920
epoch 362, loss:26.5350
epoch 363, loss:26.4788
epoch 364, loss:26.4233
epoch 365, loss:26.3688
epoch 366, loss:26.3150
epoch 367, loss:26.2618
epoch 368, loss:26.2096
epoch 369, loss:26.1580
epoch 370, loss:26.1073
epoch 371, loss:26.0573
epoch 372, loss:26.0083
epoch 373, loss:25.9600
epoch 374, loss:25.9126
epoch 375, loss:25.8660
epoch 376, loss:25.8203
epoch 377, loss:25.7755
epoch 378, loss:25.7316
epoch 379, loss:25.6884
epoch 380, loss:25.6461
epoch 381, loss:25.6045
epoch 382, loss:25.5637
epoch 383, loss:25.5236
epoch 384, loss:25.4842
epoch 385, loss:25.4455
epoch 386, loss:25.4075
epoch 387, loss:25.3702
epoch 388, loss:25.3336
epoch 389, loss:25.2977
epoch 390, loss:25.2623
epoch 391, loss:25.2276
epoch 392, loss:25.1936
epoch 393, loss:25.1603
epoch 394, loss:25.1278
epoch 395, loss:25.0959
epoch 396, loss:25.0646
epoch 397, loss:25.0339
epoch 398, loss:25.0039
epoch 399, loss:24.9744
epoch 400, loss:24.9454
epoch 401, loss:24.9170
epoch 402, loss:24.8892
epoch 403, loss:24.8619
epoch 404, loss:24.8352
epoch 405, loss:24.8090
epoch 406, loss:24.7834
epoch 407, loss:24.7582
epoch 408, loss:24.7336
epoch 409, loss:24.7094
epoch 410, loss:24.6857
epoch 411, loss:24.6625
epoch 412, loss:24.6397
epoch 413, loss:24.6174
epoch 414, loss:24.5956
epoch 415, loss:24.5741
epoch 416, loss:24.5532
epoch 417, loss:24.5327
epoch 418, loss:24.5127
epoch 419, loss:24.4930
epoch 420, loss:24.4737
epoch 421, loss:24.4548
epoch 422, loss:24.4364
epoch 423, loss:24.4182
epoch 424, loss:24.4005
epoch 425, loss:24.3831
epoch 426, loss:24.3661
epoch 427, loss:24.3494
epoch 428, loss:24.3331
epoch 429, loss:24.3171
epoch 430, loss:24.3014
epoch 431, loss:24.2862
epoch 432, loss:24.2713
epoch 433, loss:24.2568
epoch 434, loss:24.2425
epoch 435, loss:24.2286
epoch 436, loss:24.2150
epoch 437, loss:24.2017
epoch 438, loss:24.1887
epoch 439, loss:24.1761
epoch 440, loss:24.1637
epoch 441, loss:24.1516
epoch 442, loss:24.1398
epoch 443, loss:24.1283
epoch 444, loss:24.1170
epoch 445, loss:24.1060
epoch 446, loss:24.0952
epoch 447, loss:24.0846
epoch 448, loss:24.0743
epoch 449, loss:24.0642
epoch 450, loss:24.0544
epoch 451, loss:24.0447
epoch 452, loss:24.0353
epoch 453, loss:24.0261
epoch 454, loss:24.0171
epoch 455, loss:24.0083
epoch 456, loss:23.9997
epoch 457, loss:23.9913
epoch 458, loss:23.9831
epoch 459, loss:23.9751
epoch 460, loss:23.9673
epoch 461, loss:23.9597
epoch 462, loss:23.9522
epoch 463, loss:23.9449
epoch 464, loss:23.9378
epoch 465, loss:23.9308
epoch 466, loss:23.9240
epoch 467, loss:23.9173
epoch 468, loss:23.9108
epoch 469, loss:23.9045
epoch 470, loss:23.8983
epoch 471, loss:23.8922
epoch 472, loss:23.8863
epoch 473, loss:23.8805
epoch 474, loss:23.8749
epoch 475, loss:23.8694
epoch 476, loss:23.8640
epoch 477, loss:23.8587
epoch 478, loss:23.8537
epoch 479, loss:23.8488
epoch 480, loss:23.8439
epoch 481, loss:23.8391
epoch 482, loss:23.8345
epoch 483, loss:23.8299
epoch 484, loss:23.8255
epoch 485, loss:23.8212
epoch 486, loss:23.8169
epoch 487, loss:23.8128
epoch 488, loss:23.8087
epoch 489, loss:23.8048
epoch 490, loss:23.8009
epoch 491, loss:23.7972
epoch 492, loss:23.7935
epoch 493, loss:23.7899
epoch 494, loss:23.7864
epoch 495, loss:23.7829
epoch 496, loss:23.7796
epoch 497, loss:23.7763
epoch 498, loss:23.7731
epoch 499, loss:23.7700

In [22]:
#convert numpy to tensor
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
#Stop tracking the gradient by calling detach since we don't use it anymore
y_pred = model(X_test_tensor).detach().numpy()

print_evaluation_metrics(y_test, y_pred)

Mean Squared Error: 22.0893
Root Mean Squared Error: 4.6999
Mean Absolute Error: 3.6132

Attempt to improve the performance by adjusting the number of neurons and optimization algorithm

In [23]:
# increase the number of neurons to 50
improved_model = LinearRegressionModel(input_size = X_train.shape[1], hidden_size = 50, output_size = 1)
loss = nn.MSELoss()
# change the optimization algorithm to stochastic gradient descent (sgd) with a learning rate of 0.001
optimizer = torch.optim.SGD(improved_model.parameters(), lr=0.001)
train_PyTorch_model(improved_model, loss, optimizer, X_train, y_train)

epoch 0, loss:15625.0342
epoch 1, loss:15392.9805
epoch 2, loss:15133.4404
epoch 3, loss:14784.1387
epoch 4, loss:14268.7393
epoch 5, loss:13483.0684
epoch 6, loss:12293.9219
epoch 7, loss:10570.8906
epoch 8, loss:8279.9658
epoch 9, loss:5640.2803
epoch 10, loss:3194.5847
epoch 11, loss:1519.7438
epoch 12, loss:726.6826
epoch 13, loss:466.9098
epoch 14, loss:399.0886
epoch 15, loss:378.0785
epoch 16, loss:366.2358
epoch 17, loss:356.2216
epoch 18, loss:346.7849
epoch 19, loss:337.7145
epoch 20, loss:328.9665
epoch 21, loss:320.5220
epoch 22, loss:312.3680
epoch 23, loss:304.4923
epoch 24, loss:296.8830
epoch 25, loss:289.5294
epoch 26, loss:282.4214
epoch 27, loss:275.5488
epoch 28, loss:268.9025
epoch 29, loss:262.4736
epoch 30, loss:256.2535
epoch 31, loss:250.2342
epoch 32, loss:244.4081
epoch 33, loss:238.7679
epoch 34, loss:233.3063
epoch 35, loss:228.0169
epoch 36, loss:222.8933
epoch 37, loss:217.9293
epoch 38, loss:213.1190
epoch 39, loss:208.4570
epoch 40, loss:203.9378
epoch 41, loss:199.5561
epoch 42, loss:195.3072
epoch 43, loss:191.1862
epoch 44, loss:187.1888
epoch 45, loss:183.3104
epoch 46, loss:179.5470
epoch 47, loss:175.8945
epoch 48, loss:172.3491
epoch 49, loss:168.9070
epoch 50, loss:165.5648
epoch 51, loss:162.3191
epoch 52, loss:159.1665
epoch 53, loss:156.1039
epoch 54, loss:153.1283
epoch 55, loss:150.2369
epoch 56, loss:147.4266
epoch 57, loss:144.6949
epoch 58, loss:142.0391
epoch 59, loss:139.4568
epoch 60, loss:136.9455
epoch 61, loss:134.5029
epoch 62, loss:132.1268
epoch 63, loss:129.8150
epoch 64, loss:127.5654
epoch 65, loss:125.3761
epoch 66, loss:123.2453
epoch 67, loss:121.1708
epoch 68, loss:119.1511
epoch 69, loss:117.1843
epoch 70, loss:115.2688
epoch 71, loss:113.4032
epoch 72, loss:111.5856
epoch 73, loss:109.8148
epoch 74, loss:108.0891
epoch 75, loss:106.4075
epoch 76, loss:104.7683
epoch 77, loss:103.1705
epoch 78, loss:101.6126
epoch 79, loss:100.0936
epoch 80, loss:98.6122
epoch 81, loss:97.1674
epoch 82, loss:95.7581
epoch 83, loss:94.3831
epoch 84, loss:93.0417
epoch 85, loss:91.7327
epoch 86, loss:90.4552
epoch 87, loss:89.2083
epoch 88, loss:87.9912
epoch 89, loss:86.8030
epoch 90, loss:85.6428
epoch 91, loss:84.5099
epoch 92, loss:83.4036
epoch 93, loss:82.3230
epoch 94, loss:81.2675
epoch 95, loss:80.2363
epoch 96, loss:79.2289
epoch 97, loss:78.2444
epoch 98, loss:77.2824
epoch 99, loss:76.3423
epoch 100, loss:75.4233
epoch 101, loss:74.5250
epoch 102, loss:73.6468
epoch 103, loss:72.7882
epoch 104, loss:71.9486
epoch 105, loss:71.1276
epoch 106, loss:70.3246
epoch 107, loss:69.5393
epoch 108, loss:68.7710
epoch 109, loss:68.0195
epoch 110, loss:67.2842
epoch 111, loss:66.5648
epoch 112, loss:65.8607
epoch 113, loss:65.1718
epoch 114, loss:64.4975
epoch 115, loss:63.8375
epoch 116, loss:63.1915
epoch 117, loss:62.5590
epoch 118, loss:61.9397
epoch 119, loss:61.3334
epoch 120, loss:60.7397
epoch 121, loss:60.1583
epoch 122, loss:59.5888
epoch 123, loss:59.0311
epoch 124, loss:58.4847
epoch 125, loss:57.9495
epoch 126, loss:57.4252
epoch 127, loss:56.9114
epoch 128, loss:56.4080
epoch 129, loss:55.9147
epoch 130, loss:55.4312
epoch 131, loss:54.9573
epoch 132, loss:54.4929
epoch 133, loss:54.0375
epoch 134, loss:53.5912
epoch 135, loss:53.1535
epoch 136, loss:52.7244
epoch 137, loss:52.3036
epoch 138, loss:51.8910
epoch 139, loss:51.4863
epoch 140, loss:51.0894
epoch 141, loss:50.7001
epoch 142, loss:50.3181
epoch 143, loss:49.9434
epoch 144, loss:49.5758
epoch 145, loss:49.2151
epoch 146, loss:48.8611
epoch 147, loss:48.5138
epoch 148, loss:48.1728
epoch 149, loss:47.8382
epoch 150, loss:47.5098
epoch 151, loss:47.1873
epoch 152, loss:46.8708
epoch 153, loss:46.5599
epoch 154, loss:46.2547
epoch 155, loss:45.9550
epoch 156, loss:45.6607
epoch 157, loss:45.3716
epoch 158, loss:45.0877
epoch 159, loss:44.8088
epoch 160, loss:44.5347
epoch 161, loss:44.2655
epoch 162, loss:44.0010
epoch 163, loss:43.7411
epoch 164, loss:43.4857
epoch 165, loss:43.2346
epoch 166, loss:42.9879
epoch 167, loss:42.7454
epoch 168, loss:42.5070
epoch 169, loss:42.2726
epoch 170, loss:42.0421
epoch 171, loss:41.8155
epoch 172, loss:41.5927
epoch 173, loss:41.3736
epoch 174, loss:41.1581
epoch 175, loss:40.9461
epoch 176, loss:40.7377
epoch 177, loss:40.5326
epoch 178, loss:40.3308
epoch 179, loss:40.1322
epoch 180, loss:39.9369
epoch 181, loss:39.7446
epoch 182, loss:39.5555
epoch 183, loss:39.3693
epoch 184, loss:39.1860
epoch 185, loss:39.0056
epoch 186, loss:38.8280
epoch 187, loss:38.6532
epoch 188, loss:38.4810
epoch 189, loss:38.3115
epoch 190, loss:38.1446
epoch 191, loss:37.9802
epoch 192, loss:37.8183
epoch 193, loss:37.6588
epoch 194, loss:37.5017
epoch 195, loss:37.3470
epoch 196, loss:37.1945
epoch 197, loss:37.0443
epoch 198, loss:36.8963
epoch 199, loss:36.7504
epoch 200, loss:36.6067
epoch 201, loss:36.4650
epoch 202, loss:36.3254
epoch 203, loss:36.1877
epoch 204, loss:36.0521
epoch 205, loss:35.9183
epoch 206, loss:35.7864
epoch 207, loss:35.6564
epoch 208, loss:35.5282
epoch 209, loss:35.4018
epoch 210, loss:35.2771
epoch 211, loss:35.1542
epoch 212, loss:35.0329
epoch 213, loss:34.9132
epoch 214, loss:34.7952
epoch 215, loss:34.6788
epoch 216, loss:34.5640
epoch 217, loss:34.4507
epoch 218, loss:34.3389
epoch 219, loss:34.2285
epoch 220, loss:34.1196
epoch 221, loss:34.0122
epoch 222, loss:33.9061
epoch 223, loss:33.8015
epoch 224, loss:33.6981
epoch 225, loss:33.5961
epoch 226, loss:33.4954
epoch 227, loss:33.3960
epoch 228, loss:33.2979
epoch 229, loss:33.2010
epoch 230, loss:33.1053
epoch 231, loss:33.0108
epoch 232, loss:32.9175
epoch 233, loss:32.8254
epoch 234, loss:32.7344
epoch 235, loss:32.6445
epoch 236, loss:32.5557
epoch 237, loss:32.4680
epoch 238, loss:32.3813
epoch 239, loss:32.2958
epoch 240, loss:32.2112
epoch 241, loss:32.1277
epoch 242, loss:32.0451
epoch 243, loss:31.9635
epoch 244, loss:31.8829
epoch 245, loss:31.8033
epoch 246, loss:31.7246
epoch 247, loss:31.6468
epoch 248, loss:31.5699
epoch 249, loss:31.4939
epoch 250, loss:31.4188
epoch 251, loss:31.3446
epoch 252, loss:31.2712
epoch 253, loss:31.1986
epoch 254, loss:31.1269
epoch 255, loss:31.0560
epoch 256, loss:30.9859
epoch 257, loss:30.9166
epoch 258, loss:30.8481
epoch 259, loss:30.7803
epoch 260, loss:30.7133
epoch 261, loss:30.6471
epoch 262, loss:30.5815
epoch 263, loss:30.5167
epoch 264, loss:30.4527
epoch 265, loss:30.3893
epoch 266, loss:30.3266
epoch 267, loss:30.2646
epoch 268, loss:30.2032
epoch 269, loss:30.1426
epoch 270, loss:30.0826
epoch 271, loss:30.0232
epoch 272, loss:29.9645
epoch 273, loss:29.9064
epoch 274, loss:29.8489
epoch 275, loss:29.7920
epoch 276, loss:29.7358
epoch 277, loss:29.6801
epoch 278, loss:29.6250
epoch 279, loss:29.5705
epoch 280, loss:29.5166
epoch 281, loss:29.4632
epoch 282, loss:29.4104
epoch 283, loss:29.3582
epoch 284, loss:29.3065
epoch 285, loss:29.2553
epoch 286, loss:29.2046
epoch 287, loss:29.1545
epoch 288, loss:29.1049
epoch 289, loss:29.0558
epoch 290, loss:29.0072
epoch 291, loss:28.9591
epoch 292, loss:28.9115
epoch 293, loss:28.8643
epoch 294, loss:28.8177
epoch 295, loss:28.7715
epoch 296, loss:28.7258
epoch 297, loss:28.6805
epoch 298, loss:28.6357
epoch 299, loss:28.5914
epoch 300, loss:28.5475
epoch 301, loss:28.5040
epoch 302, loss:28.4609
epoch 303, loss:28.4183
epoch 304, loss:28.3761
epoch 305, loss:28.3344
epoch 306, loss:28.2930
epoch 307, loss:28.2520
epoch 308, loss:28.2115
epoch 309, loss:28.1713
epoch 310, loss:28.1316
epoch 311, loss:28.0922
epoch 312, loss:28.0532
epoch 313, loss:28.0146
epoch 314, loss:27.9764
epoch 315, loss:27.9385
epoch 316, loss:27.9011
epoch 317, loss:27.8639
epoch 318, loss:27.8272
epoch 319, loss:27.7908
epoch 320, loss:27.7547
epoch 321, loss:27.7190
epoch 322, loss:27.6836
epoch 323, loss:27.6486
epoch 324, loss:27.6139
epoch 325, loss:27.5795
epoch 326, loss:27.5455
epoch 327, loss:27.5118
epoch 328, loss:27.4784
epoch 329, loss:27.4453
epoch 330, loss:27.4125
epoch 331, loss:27.3801
epoch 332, loss:27.3479
epoch 333, loss:27.3161
epoch 334, loss:27.2846
epoch 335, loss:27.2533
epoch 336, loss:27.2223
epoch 337, loss:27.1917
epoch 338, loss:27.1613
epoch 339, loss:27.1312
epoch 340, loss:27.1014
epoch 341, loss:27.0719
epoch 342, loss:27.0426
epoch 343, loss:27.0136
epoch 344, loss:26.9849
epoch 345, loss:26.9565
epoch 346, loss:26.9283
epoch 347, loss:26.9003
epoch 348, loss:26.8727
epoch 349, loss:26.8453
epoch 350, loss:26.8181
epoch 351, loss:26.7912
epoch 352, loss:26.7645
epoch 353, loss:26.7381
epoch 354, loss:26.7119
epoch 355, loss:26.6860
epoch 356, loss:26.6603
epoch 357, loss:26.6348
epoch 358, loss:26.6096
epoch 359, loss:26.5846
epoch 360, loss:26.5598
epoch 361, loss:26.5353
epoch 362, loss:26.5109
epoch 363, loss:26.4868
epoch 364, loss:26.4630
epoch 365, loss:26.4393
epoch 366, loss:26.4158
epoch 367, loss:26.3926
epoch 368, loss:26.3696
epoch 369, loss:26.3468
epoch 370, loss:26.3241
epoch 371, loss:26.3017
epoch 372, loss:26.2795
epoch 373, loss:26.2575
epoch 374, loss:26.2357
epoch 375, loss:26.2141
epoch 376, loss:26.1926
epoch 377, loss:26.1714
epoch 378, loss:26.1504
epoch 379, loss:26.1295
epoch 380, loss:26.1088
epoch 381, loss:26.0883
epoch 382, loss:26.0680
epoch 383, loss:26.0479
epoch 384, loss:26.0280
epoch 385, loss:26.0082
epoch 386, loss:25.9886
epoch 387, loss:25.9692
epoch 388, loss:25.9499
epoch 389, loss:25.9309
epoch 390, loss:25.9120
epoch 391, loss:25.8932
epoch 392, loss:25.8746
epoch 393, loss:25.8562
epoch 394, loss:25.8380
epoch 395, loss:25.8199
epoch 396, loss:25.8019
epoch 397, loss:25.7842
epoch 398, loss:25.7665
epoch 399, loss:25.7491
epoch 400, loss:25.7317
epoch 401, loss:25.7146
epoch 402, loss:25.6976
epoch 403, loss:25.6807
epoch 404, loss:25.6640
epoch 405, loss:25.6474
epoch 406, loss:25.6310
epoch 407, loss:25.6147
epoch 408, loss:25.5985
epoch 409, loss:25.5825
epoch 410, loss:25.5666
epoch 411, loss:25.5509
epoch 412, loss:25.5353
epoch 413, loss:25.5198
epoch 414, loss:25.5045
epoch 415, loss:25.4893
epoch 416, loss:25.4742
epoch 417, loss:25.4593
epoch 418, loss:25.4445
epoch 419, loss:25.4298
epoch 420, loss:25.4152
epoch 421, loss:25.4008
epoch 422, loss:25.3865
epoch 423, loss:25.3723
epoch 424, loss:25.3582
epoch 425, loss:25.3443
epoch 426, loss:25.3305
epoch 427, loss:25.3167
epoch 428, loss:25.3032
epoch 429, loss:25.2897
epoch 430, loss:25.2763
epoch 431, loss:25.2631
epoch 432, loss:25.2499
epoch 433, loss:25.2369
epoch 434, loss:25.2240
epoch 435, loss:25.2112
epoch 436, loss:25.1985
epoch 437, loss:25.1859
epoch 438, loss:25.1734
epoch 439, loss:25.1610
epoch 440, loss:25.1487
epoch 441, loss:25.1366
epoch 442, loss:25.1245
epoch 443, loss:25.1125
epoch 444, loss:25.1007
epoch 445, loss:25.0889
epoch 446, loss:25.0772
epoch 447, loss:25.0656
epoch 448, loss:25.0542
epoch 449, loss:25.0428
epoch 450, loss:25.0315
epoch 451, loss:25.0203
epoch 452, loss:25.0092
epoch 453, loss:24.9982
epoch 454, loss:24.9872
epoch 455, loss:24.9764
epoch 456, loss:24.9657
epoch 457, loss:24.9550
epoch 458, loss:24.9445
epoch 459, loss:24.9340
epoch 460, loss:24.9236
epoch 461, loss:24.9133
epoch 462, loss:24.9031
epoch 463, loss:24.8929
epoch 464, loss:24.8829
epoch 465, loss:24.8729
epoch 466, loss:24.8630
epoch 467, loss:24.8532
epoch 468, loss:24.8435
epoch 469, loss:24.8338
epoch 470, loss:24.8242
epoch 471, loss:24.8147
epoch 472, loss:24.8053
epoch 473, loss:24.7960
epoch 474, loss:24.7867
epoch 475, loss:24.7775
epoch 476, loss:24.7684
epoch 477, loss:24.7593
epoch 478, loss:24.7504
epoch 479, loss:24.7415
epoch 480, loss:24.7326
epoch 481, loss:24.7239
epoch 482, loss:24.7152
epoch 483, loss:24.7065
epoch 484, loss:24.6980
epoch 485, loss:24.6895
epoch 486, loss:24.6811
epoch 487, loss:24.6727
epoch 488, loss:24.6644
epoch 489, loss:24.6562
epoch 490, loss:24.6480
epoch 491, loss:24.6399
epoch 492, loss:24.6318
epoch 493, loss:24.6239
epoch 494, loss:24.6159
epoch 495, loss:24.6081
epoch 496, loss:24.6003
epoch 497, loss:24.5925
epoch 498, loss:24.5848
epoch 499, loss:24.5772

In [24]:
#convert numpy to tensor
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
#Stop tracking the gradient by calling detach since we don't use it anymore
y_pred = improved_model(X_test_tensor).detach().numpy()

print_evaluation_metrics(y_test, y_pred)

Mean Squared Error: 23.1341
Root Mean Squared Error: 4.8098
Mean Absolute Error: 3.7710